# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/titlois/Documents/s3/Synthèse d'images/projet/IMACMAN"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/titlois/Documents/s3/Synthèse d'images/projet/IMACMAN"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/titlois/Documents/s3/Synthèse d'images/projet/IMACMAN/CMakeFiles" "/home/titlois/Documents/s3/Synthèse d'images/projet/IMACMAN/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/titlois/Documents/s3/Synthèse d'images/projet/IMACMAN/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glimac

# Build rule for target.
glimac: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glimac
.PHONY : glimac

# fast build rule for target.
glimac/fast:
	$(MAKE) -f glimac/CMakeFiles/glimac.dir/build.make glimac/CMakeFiles/glimac.dir/build
.PHONY : glimac/fast

#=============================================================================
# Target rules for targets named TP3_dessin_lune

# Build rule for target.
TP3_dessin_lune: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TP3_dessin_lune
.PHONY : TP3_dessin_lune

# fast build rule for target.
TP3_dessin_lune/fast:
	$(MAKE) -f TP3/CMakeFiles/TP3_dessin_lune.dir/build.make TP3/CMakeFiles/TP3_dessin_lune.dir/build
.PHONY : TP3_dessin_lune/fast

#=============================================================================
# Target rules for targets named TP3_dessin_sphere

# Build rule for target.
TP3_dessin_sphere: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TP3_dessin_sphere
.PHONY : TP3_dessin_sphere

# fast build rule for target.
TP3_dessin_sphere/fast:
	$(MAKE) -f TP3/CMakeFiles/TP3_dessin_sphere.dir/build.make TP3/CMakeFiles/TP3_dessin_sphere.dir/build
.PHONY : TP3_dessin_sphere/fast

#=============================================================================
# Target rules for targets named TP3_dessin_terre

# Build rule for target.
TP3_dessin_terre: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TP3_dessin_terre
.PHONY : TP3_dessin_terre

# fast build rule for target.
TP3_dessin_terre/fast:
	$(MAKE) -f TP3/CMakeFiles/TP3_dessin_terre.dir/build.make TP3/CMakeFiles/TP3_dessin_terre.dir/build
.PHONY : TP3_dessin_terre/fast

#=============================================================================
# Target rules for targets named TP3_SDLtemplate

# Build rule for target.
TP3_SDLtemplate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TP3_SDLtemplate
.PHONY : TP3_SDLtemplate

# fast build rule for target.
TP3_SDLtemplate/fast:
	$(MAKE) -f TP3/CMakeFiles/TP3_SDLtemplate.dir/build.make TP3/CMakeFiles/TP3_SDLtemplate.dir/build
.PHONY : TP3_SDLtemplate/fast

#=============================================================================
# Target rules for targets named TP3_dessin_menu

# Build rule for target.
TP3_dessin_menu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TP3_dessin_menu
.PHONY : TP3_dessin_menu

# fast build rule for target.
TP3_dessin_menu/fast:
	$(MAKE) -f TP3/CMakeFiles/TP3_dessin_menu.dir/build.make TP3/CMakeFiles/TP3_dessin_menu.dir/build
.PHONY : TP3_dessin_menu/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... glimac"
	@echo "... TP3_dessin_lune"
	@echo "... TP3_dessin_sphere"
	@echo "... TP3_dessin_terre"
	@echo "... TP3_SDLtemplate"
	@echo "... TP3_dessin_menu"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

